load("@rules_python//python:defs.bzl", "py_binary")
load("//rules:clang_tidy.bzl", "tidy_regex_flag", "tidy_source_flag")

test_suite(
    name = "sanity_checks",
    tests = [
        "//toolchains:tool_versions_test",
    ],
)

# By default we will just accept all goldfish thingies.
tidy_source_flag(
    name = "clang_tidy_check_files",
    build_setting_default = "goldfish",
    visibility = ["//visibility:public"],
)

tidy_regex_flag(
    name = "clang_tidy_regex",
    build_setting_default = "",
    visibility = ["//visibility:public"],
)

filegroup(
    name = "default_tidy_config",
    srcs = [".clang-tidy"],
    visibility = ["//visibility:public"],
)

label_flag(
    name = "clang_tidy_config",
    build_setting_default = ":default_tidy_config",
    visibility = ["//visibility:public"],
)

py_binary(
    name = "gen-cc-snippet",
    srcs = ["utils/gen_cc_snippet.py"],
    main = "gen_cc_snippet.py",
    visibility = ["//visibility:public"],
)

py_binary(
    name = "run-clang-tidy",
    srcs = ["utils/run_clang_tidy.py"],
    main = "run_clang_tidy.py",
    visibility = ["//visibility:public"],
)
