load("@rules_license//rules:license.bzl", "license")
load("@rules_python//python:pip.bzl", "compile_pip_requirements")
load("//rules:clang_tidy.bzl", "tidy_exclude_tags_flag", "tidy_regex_flag", "tidy_source_flag")

package(
    default_applicable_licenses = [":license"],
)

license(
    name = "license",
    package_name = "goldfish_build",
    copyright_notice = "Copyright 2024 - The Android Open Source Project",
    license_kinds = ["@rules_license//licenses/spdx:Apache-2.0"],
    license_text = "LICENSE",  # Using OWNERS as a placeholder text file since no LICENSE exists here
    visibility = ["//visibility:public"],
)

exports_files([
    "LICENSE",
    "registry/modules/goldfish/0.0.1/MODULE.bazel",
])

test_suite(
    name = "sanity_checks",
    tests = [
        "//toolchains:tool_versions_test",
    ],
)

# Here are the various flags used for our clang-tidy rules
# By default we will just accept all goldfish thingies.
tidy_source_flag(
    name = "clang_tidy_check_files",
    build_setting_default = "goldfish",
    visibility = ["//visibility:public"],
)

tidy_regex_flag(
    name = "clang_tidy_regex",
    build_setting_default = "",
    visibility = ["//visibility:public"],
)

filegroup(
    name = "default_tidy_config",
    srcs = [".clang-tidy"],
    visibility = ["//visibility:public"],
)

label_flag(
    name = "clang_tidy_config",
    build_setting_default = ":default_tidy_config",
    visibility = ["//visibility:public"],
)

tidy_exclude_tags_flag(
    name = "clang_tidy_exclude_tags",
    build_setting_default = [],
    visibility = ["//visibility:public"],
)

# This rule adds a convenient way to update the requirements file.
# If you make changes to "requirements.in" you will have to run this target.
compile_pip_requirements(
    name = "requirements",
    src = "requirements.in",
    requirements_txt = "requirements_lock.txt",
)
