# Copyright 2024 - The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the',  help='License');
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an',  help='AS IS' BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""The android emulator."""

module(
    name = "android_emulator",
    version = "0.0.1",
)

include("//build/bazel/toolchains:toolchain.MODULE.bazel")

custom_toolchains = use_extension("@goldfish_build//extensions:toolchain.bzl", "toolchain")
custom_toolchains.clang(root_path = "prebuilts/clang/host")
custom_toolchains.rust(root_path = "prebuilts/rust")
custom_toolchains.java(
    root_path = "prebuilts/studio/jdk",
    version = "jdk17",
)
use_repo(custom_toolchains, "gcc_lib")

bazel_dep(name = "goldfish", version = "0.0.1")
bazel_dep(name = "qemu", version = "0.0.1")
bazel_dep(name = "breakpad", version = "0.0.1")
bazel_dep(name = "pkg-config", version = "0.29.2")
bazel_dep(name = "protobuf", version = "32.1")
bazel_dep(name = "boringssl", version = "0.20250415.0")
bazel_dep(name = "tink_cc", version = "2.4.0")

# repo_name override needed by @grpc
bazel_dep(name = "protoc-gen-validate", version = "1.2.1.bcr.1", repo_name = "com_envoyproxy_protoc_gen_validate")

# Dep of GRPC but override here
# Use local registry version to address https://github.com/bazelbuild/bazel/issues/26922
bazel_dep(name = "c-ares", version = "1.19.1.aemu")
bazel_dep(name = "grpc-java", version = "1.75.0")
bazel_dep(name = "grpc", version = "1.74.1.aemu")

# These are only needed for AMC
# TODO(whollins): get them from @qemu module instead somehow
bazel_dep(name = "zlib", version = "1.3.1.bcr.5")
bazel_dep(name = "pcre2", version = "10.46-DEV")
bazel_dep(name = "glib", version = "2.82.2.bcr.5.aemu")
bazel_dep(name = "dtc", version = "0.0.1")
bazel_dep(name = "pixman", version = "0.0.1")
bazel_dep(name = "aemu", version = "0.0.1")
bazel_dep(name = "crosvm", version = "0.0.1")

# These are all deps of lavapipe?
bazel_dep(name = "libdrm", version = "2.4.110")
bazel_dep(name = "libexpat", version = "2.7.1.aemu")
bazel_dep(name = "libffi", version = "3.4.7.bcr.3.aemu")
bazel_dep(name = "libjpeg_turbo", version = "2.1.91")
bazel_dep(name = "libx11", version = "1.8.12.bcr.3")
bazel_dep(name = "libxrandr", version = "1.5.4")
bazel_dep(name = "libxshmfence", version = "1.3.3")
bazel_dep(name = "xorgproto", version = "2024.1.bcr.1")
bazel_dep(name = "libxcb", version = "1.17.0.bcr.2")
bazel_dep(name = "wayland", version = "1.22.0")
bazel_dep(name = "qt_prebuilt", version = "6.5.3")
local_path_override(
    module_name = "qt_prebuilt",
    path = "prebuilts/android-emulator-build/qt",
)

bazel_dep(name = "goldfish_test", version = "0.0.1")
local_path_override(
    module_name = "goldfish_test",
    path = "third_party/adt-infra/goldfish_test",
)

run_suite = use_extension("@goldfish_test//tests:suite_runner.bzl", "run_suite")
run_suite.ets(
    name = "ets",
    goldfish_zip = "@goldfish//emulator:release",
)
use_repo(run_suite, "ets")

# Enable Java gRPC compilation
bazel_dep(name = "rules_jvm_external", version = "6.0")

maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
use_repo(maven, "maven")

maven.install(
    artifacts = [
        # Rerun REPIN=1 bazel run @maven//:pin, and update
        # the lock_file if you change this list.
        "com.google.api.grpc:grpc-google-cloud-pubsub-v1:1.125.0",
        "com.google.api.grpc:proto-google-cloud-pubsub-v1:1.125.0",
        "com.squareup.okhttp:okhttp:2.7.5",
        "com.squareup.okio:okio:2.10.0",
        "io.grpc:grpc-core:1.75.0",
        "io.grpc:grpc-android:1.75.0",
        "io.grpc:grpc-stub:1.75.0",
    ],
    lock_file = "@goldfish_build//:maven_install.json",
    repositories = [
        "https://repo.maven.apache.org/maven2/",
        "https://maven.google.com",
    ],
    strict_visibility = True,
)

gcs_archive = use_repo_rule("@rules_gcs//gcs:repo_rules.bzl", "gcs_archive")

gcs_archive(
    name = "mac-arm64-platform-tools",
    build_file = "//hardware/generic/goldfish/emulator/sdk/platform-tools/mac-arm64-platform-tools:platform-tools.BUILD",
    sha256 = "45f3fdc096a584aa83440d0437ba5673fc693d17784293416cdb99213afe07cd",
    url = "gs://emu-next-bazel/ab/aosp-sdk-release/sdk_mac/13278306/sdk-repo-darwin-platform-tools-13278306.zip",
)

gcs_archive(
    name = "linux-platform-tools",
    build_file = "//hardware/generic/goldfish/emulator/sdk/platform-tools/linux-platform-tools:platform-tools.BUILD",
    sha256 = "5c377d32e7ba0c1f982417ec588c33d8e379141e806c46c2de26cf42fe6ed51e",
    url = "gs://emu-next-bazel/ab/aosp-sdk-release/sdk/13278306/sdk-repo-linux-platform-tools-13278306.zip",
)

gcs_archive(
    name = "linux-build-tools",
    build_file = "//hardware/generic/goldfish/emulator/sdk/build-tools/linux-build-tools:build-tools.BUILD",
    sha256 = "321e687caa570210bf4acd80e8cfbe901d17368d83f51976ccbba3656093fe2b",
    url = "gs://emu-next-bazel/ab/aosp-sdk-release/sdk/13278306/sdk-repo-linux-build-tools-13278306.zip",
)

gcs_archive(
    name = "mac-arm64-build-tools",
    build_file = "//hardware/generic/goldfish/emulator/sdk/build-tools/mac-arm64-build-tools:build-tools.BUILD",
    sha256 = "40f143dda6d1d4b7028e45e96c5c5fe18227252880679465218881bd947c44f9",
    url = "gs://emu-next-bazel/ab/aosp-sdk-release/sdk_mac/13278306/sdk-repo-darwin-build-tools-13278306.zip",
)

gcs_archive(
    name = "test_seq_linux",
    build_file = "//hardware/generic/goldfish/emulator/tests:test_seq_linux.BUILD",
    sha256 = "ffebc35e4c811facc921b0f92294211bcfa485e26ce2e880b0aa65b2fb4a2501",
    url = "gs://emu-next-bazel/test_seq/test_seq_20251119_0840_RC00/test_seq_linux.zip",
)

gcs_archive(
    name = "test_seq_mac_arm64",
    build_file = "//hardware/generic/goldfish/emulator/tests:test_seq_mac_arm64.BUILD",
    sha256 = "c4eddb017a5755955d494960a127125c30e4edcf3ad6476c65753e51ed9c5b59",
    url = "gs://emu-next-bazel/test_seq/test_seq_20251119_0840_RC00/test_seq_darwin_arm64.zip",
)

gcs_archive(
    name = "cts-x86-64",
    build_file = "//hardware/generic/goldfish/emulator/sdk/xts/cts-x86-64:cts.BUILD",
    sha256 = "e16721554b8e46d3138350670d83c11709dcf8bb12f50517f62ef40f0055235f",
    url = "gs://emu-next-bazel/ab/git_trunk-release/test_suites_x86_64/14236881/android-cts.zip",
)

gcs_archive(
    name = "cts-arm64",
    build_file = "//hardware/generic/goldfish/emulator/sdk/xts/cts-arm64:cts.BUILD",
    sha256 = "eb6b31ea8b61038ad4f21f4b0189c1092b3a3133161329bd71c7e6d48e41d83a",
    url = "gs://emu-next-bazel/ab/git_trunk-release/test_suites_arm64/14236881/android-cts.zip",
)
