# Copyright 2024 - The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the',  help='License');
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an',  help='AS IS' BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""The android emulator."""

module(
    name = "android_emulator",
    version = "0.0.1",
)

bazel_dep(name = "platforms", version = "0.0.11")
bazel_dep(name = "apple_support", version = "1.21.1", repo_name = "build_bazel_apple_support")
bazel_dep(name = "bazel_skylib", version = "1.7.1")
bazel_dep(name = "rules_cc", version = "0.0.17")
bazel_dep(name = "rules_license", version = "1.0.0")
bazel_dep(name = "rules_pkg", version = "1.1.0")
bazel_dep(name = "rules_python", version = "1.4.0")
bazel_dep(name = "rules_rust", version = "0.60.0")
single_version_override(
    module_name = "rules_rust",
    patch_strip = 1,
    patches = [
        "//build/bazel/toolchains/rust:fix-generated-file-with-sibling-layout.patch",  # https://github.com/bazelbuild/rules_rust/pull/2804
    ],
)

bazel_dep(name = "with_cfg.bzl", version = "0.10.1")

bazel_dep(name = "buildifier_prebuilt", version = "8.0.3", dev_dependency = True)

bazel_dep(name = "abseil-cpp", version = "20250127.0", repo_name = "com_google_absl")
local_path_override(
    module_name = "abseil-cpp",
    path = "external/abseil-cpp",
)

bazel_dep(name = "aemu", version = "0.0.1")
local_path_override(
    module_name = "aemu",
    path = "hardware/google/aemu",
)

bazel_dep(name = "gfxstream", version = "0.0.1")
local_path_override(
    module_name = "gfxstream",
    path = "hardware/google/gfxstream",
)

new_local_repository = use_repo_rule("@bazel_tools//tools/build_defs/repo:local.bzl", "new_local_repository")

# Rust crates, note that these follow the AOSP style of naming, where every crate
# is basically @..crate..
# Once the rust team has an automated bazel generation tool, we will no longer need these.
# See b/335734830 for details
[
    new_local_repository(
        name = create,
        build_file = "//hardware/generic/goldfish/third_party/rust/crates:BUILD.{}".format(create),
        path = "external/rust/android-crates-io/crates/{}".format(create),
    )
    for create in [
        "bitflags",
        "byteorder",
        "cfg-if",
        "equivalent",
        "foldhash",
        "hashbrown",
        "itoa",
        "libc",
        "log",
        "memchr",
        "memoffset",
        "nix",
        "once_cell",
        "proc-macro2",
        "quote",
        "remain",
        "ryu",
        "serde_derive",
        "serde_json",
        "serde",
        "syn",
        "thiserror-impl",
        "thiserror",
        "unicode-ident",
        "zerocopy-derive",
        "zerocopy",
    ]
]

new_local_repository(
    name = "winapi",
    build_file = "//hardware/generic/goldfish/third_party/rust/crates:BUILD.winapi",
    path = "hardware/generic/goldfish/third_party/rust/crates/winapi",
)

new_local_repository(
    name = "winapi-x86_64-pc-windows-gnu",
    build_file = "//hardware/generic/goldfish/third_party/rust/crates:BUILD.winapi-x86_64-pc-windows-gnu",
    path = "hardware/generic/goldfish/third_party/rust/crates/winapi-x86_64-pc-windows-gnu",
)

new_local_repository(
    name = "crosvm",
    build_file = "//hardware/generic/goldfish/third_party/crosvm:BUILD",
    path = "external/crosvm",
)

bazel_dep(name = "lz4", version = "0.0.1")
local_path_override(
    module_name = "lz4",
    path = "external/lz4",
)

bazel_dep(name = "googletest", version = "head", repo_name = "com_google_googletest")
local_path_override(
    module_name = "googletest",
    path = "external/googletest",
)

register_toolchains(
    "//build/bazel/toolchains/cc/linux_clang:x64_toolchain",
    "//build/bazel/toolchains/cc/linux_clang:x64_objcopy_toolchain",
    "//build/bazel/toolchains/cc/mac_clang:x64_toolchain",
    "//build/bazel/toolchains/cc/mac_clang:arm64_toolchain",
    "//build/bazel/toolchains/cc/mac_clang:objcopy_toolchain",
    "//build/bazel/toolchains/cc/windows_clang:x64_toolchain",
    "//build/bazel/toolchains/cc/windows_clang:resource_compiler_x64",
)
