"""Toolchain dependencies and repos."""

# Keep this version in sync with "tool_versions.json"
TOOL_VERSIONS = {
    "clang": "clang-r596125",
    "rust": "1.91.1",
}

bazel_dep(name = "goldfish_build", version = "0.0.3")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "bazel_skylib", version = "1.9.0")
bazel_dep(name = "bazel_lib", version = "3.2.0")
bazel_dep(name = "bazel_jar_jar", version = "0.1.12")
bazel_dep(name = "apple_support", version = "2.2.0")

# rules_android is used by rules_kotlin and rules_jvm_external so we must override it here.
bazel_dep(name = "rules_android", version = "0.7.1.aemu")
bazel_dep(name = "rules_license", version = "1.0.0")
bazel_dep(name = "rules_pkg", version = "1.1.0")
bazel_dep(name = "rules_gcs", version = "1.0.1")
bazel_dep(name = "rules_cc", version = "0.2.16")
bazel_dep(name = "rules_python", version = "1.8.4")
bazel_dep(name = "rules_shell", version = "0.6.1")
bazel_dep(name = "rules_go", version = "0.60.0")
bazel_dep(name = "rules_java", version = "9.3.0")
bazel_dep(name = "rules_kotlin", version = "2.2.2")
bazel_dep(name = "rules_rust", version = "0.68.1.aemu")
bazel_dep(name = "gazelle", version = "0.47.0")

# rules_proto is deprecated by protobuf
bazel_dep(name = "rules_proto", version = "7.1.0")

# Note that the protobuf version must be compatible (the same) as the one used
# by rules_android (currently used by @goldfish)
bazel_dep(name = "protobuf", version = "33.4")
bazel_dep(name = "with_cfg.bzl", version = "0.14.1")

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    is_default = True,
    python_version = "3.10",
)

rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(
    extra_target_triples = [
        "aarch64-apple-darwin",
        "aarch64-unknown-linux-gnu",
        "aarch64-pc-windows-msvc",
        "x86_64-unknown-linux-gnu",
        "x86_64-pc-windows-msvc",
    ],
    rustfmt_version = TOOL_VERSIONS["rust"],
    versions = [TOOL_VERSIONS["rust"]],
)

go_sdk = use_extension("@rules_go//go:extensions.bzl", "go_sdk")
go_sdk.download(version = "1.26.0")

custom_toolchains = use_extension("@goldfish_build//extensions:toolchain.bzl", "toolchain")
custom_toolchains.version_file(
    label = "@goldfish_build//toolchains:tool_versions.json",
)

bazel_dep(name = "buildifier_prebuilt", version = "8.2.1.2", dev_dependency = True)

host_platform_repository = use_repo_rule("@goldfish_build//platforms:host_platform.bzl", "host_platform_repository")

host_platform_repository(
    name = "host_platform",
    host = {
        '{"os": "linux", "arch": "x64"}': "@goldfish_build//platforms:linux_x64",
        '{"os": "macos", "arch": "x64"}': "@goldfish_build//platforms:macos_x64",
        '{"os": "macos", "arch": "arm64"}': "@goldfish_build//platforms:macos_aarch64",
        '{"os": "windows", "arch": "x64"}': "@goldfish_build//platforms:windows_x64",
    },
)
