load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_binary(
    name = "hello_c",
    srcs = ["main.c"],
)

cc_binary(
    name = "hello_cpp",
    srcs = ["main.cpp"],
)

cc_binary(
    name = "nt_validation",
    srcs = ["nt_validation.c"],
)

cc_library(
    # This target used to reproduce the 'unknown target CPU' issue.
    # Replacing '-march=native' with '-march=x86-64-v3' provides a
    # stable baseline for GCE while fixing cross-compilation.
    # We also add /Dmax_align_t=double to workaround the missing
    # max_align_t in Clang's builtin headers (due to -nobuiltininc).
    name = "repro_lib",
    srcs = ["hello_dll.c"],
    copts = [
        "-march=x86-64-v3",
        # We must make sure we can compile without this flag.
        # currently it appears to be needed for clang cross compile, but
        # will work fine when doing a native compile.
        # "/Dmax_align_t=double",
    ],
)
