load("@bazel_skylib//rules:common_settings.bzl", "bool_flag")

package(default_visibility = ["//visibility:public"])

bool_flag(
    name = "hermetic_xcode",
    build_setting_default = False,
)

xcode_version(
    name = "version16_2_0_16C5032a",
    aliases = [
        "16C5032a",
        "16.2",
    ],
    default_macos_sdk_version = "16.2",
    version = "16.2.0.16C5032a",
)

xcode_config(
    name = "host_xcodes",
    default = ":version16_2_0_16C5032a",
    versions = [
        ":version16_2_0_16C5032a",
    ],
)

toolchain_type(name = "mig_toolchain_type")
