/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

/* Use futexes */
#define HAVE_FUTEX 1

#define HAVE_MEMFD_CREATE 1

#define HAVE_MKOSTEMP 1

/* Directory for shared memory temp files */
#define SHMDIR "/run/shm"

/* Enable non-standardized system API extensions */
#define _GNU_SOURCE 1

