load("@rules_license//rules:license.bzl", "license")

license(
    name = "Android-Apache-2.0",
    license_kind = "@rules_license//licenses/spdx:Apache-2.0",
    visibility = ["//visibility:public"],
)
