load("@bazel_skylib//rules:common_settings.bzl", "bool_flag")

bool_flag(
    name = "generate_gnu_debug_file",
    build_setting_default = False,
)

bool_flag(
    name = "generate_apple_dsym",
    build_setting_default = False,
)

bool_flag(
    name = "allow_strip",
    build_setting_default = False,
)
