load("@goldfish-build-pypi//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_binary", "py_test")

py_binary(
    name = "gen-cc-snippet",
    srcs = ["gen_cc_snippet.py"],
    main = "gen_cc_snippet.py",
    visibility = ["//visibility:public"],
)

py_binary(
    name = "run-clang-tidy",
    srcs = ["run_clang_tidy.py"],
    main = "run_clang_tidy.py",
    visibility = ["//visibility:public"],
    deps = [requirement("PyYAML")],
)

py_binary(
    name = "create_hermetic_packages",
    srcs = ["create_hermetic_packages.py"],
    main = "create_hermetic_packages.py",
    visibility = ["//visibility:public"],
)

py_binary(
    name = "generate_vfs",
    srcs = ["generate_vfs.py"],
    main = "generate_vfs.py",
    visibility = ["//visibility:public"],
    deps = [requirement("PyYAML")],
)

py_test(
    name = "generate_vfs_test",
    srcs = ["generate_vfs_test.py"],
    deps = [
        ":generate_vfs",
        requirement("PyYAML"),
    ],
)
