#!/usr/bin/env python3
"""
A utility script for running clang-tidy within a Bazel build environment.

This script supports three main modes of operation:
1.  **generate**: Runs clang-tidy on a single source file to generate warnings and
    fixes. It handles Bazel's specific flag passing mechanism (using '--' as a
    separator for compiler flags) and extracts the correct resource directory
    for clang.
2.  **fix**: Applies fixes from one or more YAML files generated by clang-tidy
    back to the original source files. It parses the YAML content to identify
    file paths, offsets, lengths, and replacement text, then applies these
    changes to the source code.
3.  **combine**: Merges multiple clang-tidy reports (warnings files) into a single
    output file.
"""
import argparse
import logging
import subprocess
from typing import List, Dict, Any
from pathlib import Path
import re
import sys


def _setup_logging(verbose: bool):
    """Sets up the root logger for the application."""
    level = logging.DEBUG if verbose else logging.INFO
    logging.basicConfig(
        level=level,
        format="%(asctime)s - (%(filename)s:%(lineno)d) - %(levelname)s - %(message)s ",
    )


def _create_parser() -> argparse.ArgumentParser:
    """Configures the argument parser for subcommands."""
    parser = argparse.ArgumentParser(description="Runs clang-tidy.")
    parser.add_argument(
        "-v", "--verbose", action="store_true", help="Enable verbose logging."
    )
    subparsers = parser.add_subparsers(
        dest="mode", required=True, help="Operation mode"
    )

    # --- Subcommand: generate ---
    gen_parser = subparsers.add_parser(
        "generate", help="Runs clang-tidy, generating warnings and fixes"
    )
    gen_parser.add_argument("--tidy-exe", required=True, help="Path clang-tidy.")
    gen_parser.add_argument(
        "--config-file", required=True, help="Path to the clang-tidy config"
    )
    gen_parser.add_argument(
        "--source", required=True, help="Path to the source file to check"
    )
    gen_parser.add_argument(
        "--fix",
        help="Pass on the fix flag to clang-tidy. (Note, fixes might end up in bazel sandbox and not your codebase)",
    )
    gen_parser.add_argument(
        "--export-fixes", required=True, help="Path to YAML with fixes."
    )
    gen_parser.add_argument(
        "--re",
        type=str,
        help="Sed s/old_text/new_text/g style regex to apply to rewrites. This allows you to rewrite m_foo to foo for example.",
    )
    gen_parser.add_argument(
        "--warnings_file",
        required=True,
        help="Path where all warnings and errors will be written.",
    )
    # NOTE: We do NOT define 'flags' here.
    # We rely on parse_known_args in main() to capture the compiler command
    # as 'unknown' arguments. This prevents argparse from crashing on flags
    # like -I, -D, or -o which the compiler uses but our script does not.

    # --- Subcommand: fix ---
    fix_parser = subparsers.add_parser(
        "fix", help="Apply fixes from a set of yaml files"
    )
    fix_parser.add_argument(
        "-C", type=str, help="Directory to use when applying fixes."
    )
    fix_parser.add_argument(
        "--re",
        type=str,
        help="Sed s/old_text/new_text/g style regex to apply to rewrites. This allows you to rewrite m_foo to foo for example.",
    )
    fix_parser.add_argument("yaml", nargs="+", type=str, help="A list of yaml files")

    # --- Subcommand: combine ---
    comb_parser = subparsers.add_parser("combine", help="Combine multiple reportss.")
    comb_parser.add_argument(
        "-o", "--output_file", required=True, help="Path to the output report file."
    )
    comb_parser.add_argument(
        "inputs", nargs="*", help="List of input report files to merge."
    )

    return parser


def _extract_resource_dir(compiler_flags: List[str]) -> Path:
    """Poke clang to get the actual resource directory."""
    return subprocess.check_output(
        compiler_flags + ["-print-resource-dir"],
        text=True,
    )


def _extract_regex(sed: str) -> (str, str, int):
    """Extracts a sed style regex into a pattern, replacement and count that can be used as res.sub(...)"""
    if not sed:
        return "", "", 0

    if not sed.startswith("s") or len(sed) < 4:
        raise ValueError("Invalid sed format. Expected 's/pattern/replacement/flags'")

    delimiter = sed[1]

    # Note: This assumes the user picks a delimiter that isn't IN the pattern.
    # e.g., use s|http://|...| instead of s/http:\/\//.../
    parts = sed.split(delimiter)

    if len(parts) < 4:
        raise ValueError("Invalid sed format. Missing delimiters.")

    _, pattern, replacement, raw_flags = parts[0], parts[1], parts[2], parts[3]

    # 'g' in sed means "Global" (replace all). Absence means replace First.
    # Python re.sub replaces ALL by default (count=0).
    count = 0 if "g" in raw_flags else 1
    return (pattern, replacement, count)


def _handle_generate(args: argparse.Namespace, compiler_flags: List[str]) -> None:
    """
    Runs clang-tidy on a single source file

    Args:
        args: Parsed arguments containing warnings_file, input_file, and exec_root.
        compiler_flags: The raw list of flags meant for the compiler (e.g. ['-I.', '-O2']).
    """
    # 1. Clean up compiler flags
    # If the flags start with '--', it's a separator passed by Bazel to protect
    # the flags from our argparse. We must remove it before constructing the command.
    if compiler_flags and compiler_flags[0] == "--":
        compiler_flags = compiler_flags[1:] + ["-c", args.source]

    logging.debug("Cleaned compiler flags: %s", compiler_flags)
    # Tidy will incorrectly resolve the resource_directory outside
    # of the sandbox which would result clang not finding standard headers,
    # we have to invoke clang with the complete flag configuration to get it.
    resource_dir = _extract_resource_dir(compiler_flags)
    logging.debug("Extracted resource dir: %s", resource_dir)

    tidy_cmd = [
        args.tidy_exe,
        f"--config-file={args.config_file}",
        f"--export-fixes={args.export_fixes}",
        f"-extra-arg=-resource-dir={resource_dir}",
        args.source,
    ]

    if args.fix:
        tidy_cmd.append("--fix")

    # Add compiler flags
    tidy_cmd = tidy_cmd + ["--"] + compiler_flags
    logging.debug("Running clang-tidy command: %s", " ".join(tidy_cmd))
    with open(args.warnings_file, "w") as fout:
        subprocess.run(
            tidy_cmd,
            stderr=fout,
            text=True,
            check=False,
        )
        fout.write("\n")

    # Make sure an export with fixes exist.
    if not Path(args.export_fixes).exists():
        with open(args.export_fixes, "a") as fexp:
            fexp.write("\n")

    # Next up, the YAML file contains all the internal sandbox paths
    # We need to remove those so:
    # - We are cache friendly
    # - We have an actionable result file

    # We are basically going to replace the current path which will
    # end up everywhere, and next we will strip external/some_foo+ etc.
    cwd_str = str(Path.cwd())
    logging.debug("CWD for path replacement: %s", cwd_str)

    # This matches the pattern used to strip external repo prefixes
    path_cleaner = re.compile(r"'.*\+[\/\\]")

    user_pattern = None
    if args.re:
        pattern, replacement, count = _extract_regex(args.re)
        user_pattern = re.compile(pattern)
        logging.debug(
            "Applying user regex: pattern=`%s`, replacement=`%s`, count=`%d`",
            pattern,
            replacement,
            count,
        )

    output_lines = []

    # Read and process line by line
    with open(args.export_fixes, "r") as fexp:
        for line in fexp:
            line = line.replace(cwd_str, ".")
            line = path_cleaner.sub("'", line)

            # Apply user regex ONLY to lines containing ReplacementText
            if user_pattern and line.strip().startswith("ReplacementText:"):
                line = user_pattern.sub(replacement, line, count=count)

            output_lines.append(line)

    with open(args.export_fixes, "w") as fexp:
        fexp.writelines(output_lines)


def _parse_fixes_from_yaml(yaml_files: List[str]) -> Dict[str, List[Dict[str, Any]]]:
    """Parses a list of YAML files to extract replacement information.

    This function uses a simple line-by-line parsing approach that expects
    a specific structure for replacement blocks, which is typical for
    clang-tidy's YAML output. It does not use a full YAML parser.

    Args:
        yaml_files: A list of paths to YAML files from clang-tidy.

    Returns:
        A dictionary mapping file paths to a list of fix dictionaries.
        Each fix dictionary contains 'offset', 'length', and 'text'.
    """
    fixes_map = {}
    for file_path in yaml_files:
        if not Path(file_path).exists():
            print(f"Warning: Fixes file not found: {file_path}", file=sys.stderr)
            continue
        with open(file_path, "r") as f:
            lines = f.readlines()

        i = 0
        while i < len(lines):
            line = lines[i]
            # Find the beginning of a replacements block
            if "Replacements:" in line:
                # Skip if the block is empty (e.g., "Replacements: []")
                if "[]" in line:
                    i += 1
                    continue
                i += 1
                # Process all items in the block
                while i + 3 < len(lines) and lines[i].strip().startswith("- FilePath:"):
                    try:
                        filepath = lines[i].split("'")[1]
                        offset = int(lines[i + 1].split(":")[1].strip())
                        length = int(lines[i + 2].split(":")[1].strip())

                        replacement_line = lines[i + 3]
                        val_part = replacement_line.split(":", 1)[1].strip()
                        # Handle both quoted and unquoted replacement text
                        if val_part.startswith("'") and val_part.endswith("'"):
                            replacement_text = val_part[1:-1]
                        elif val_part.startswith('"') and val_part.endswith('"'):
                            replacement_text = val_part[1:-1]
                        else:
                            # unquoted!
                            replacement_text = val_part

                        fix = {
                            "offset": offset,
                            "length": length,
                            "text": replacement_text,
                        }

                        if filepath not in fixes_map:
                            fixes_map[filepath] = []
                        fixes_map[filepath].append(fix)

                        i += 4
                    except (IndexError, ValueError) as e:
                        print(
                            f"Error parsing replacement block in {file_path} near line {i+1}: {e}",
                            file=sys.stderr,
                        )
                        i += 1
                # Continue scanning for the next 'Replacements:' block
                continue
            i += 1
    return fixes_map


def _apply_fixes(yaml_files: List[str], sed=None, cwd: str = None) -> None:
    """
    Parses clang-tidy YAML files and applies the suggested fixes to the source files.

    Args:
        yaml_files: A list of paths to YAML files containing the fixes.
        cwd: The current working directory to resolve relative paths against.
    """
    pattern, replacement, count = _extract_regex(sed)

    fixes_map = _parse_fixes_from_yaml(yaml_files)
    for filepath_str, replacements in fixes_map.items():
        filepath = Path(filepath_str)
        if cwd:
            filepath = Path(cwd) / filepath

        if not filepath.exists():
            print(f"Skipping ghost file: {filepath}", file=sys.stderr)
            continue

        logging.debug("Applying %d fixes to %s", len(replacements), filepath)

        with open(filepath, "rb") as f:
            code_bytes = f.read()

        # Sort replacements in reverse order of offset to
        # avoid corrupting byte offsets for subsequent replacements.
        replacements.sort(key=lambda x: x["offset"], reverse=True)

        for r in replacements:
            start = r["offset"]
            end = start + r["length"]
            replacement_text = re.sub(pattern, replacement, r["text"], count=count)
            replacement_bytes = replacement_text.replace("\\n", "\n").encode("utf-8")
            logging.debug(
                "Applying fix to %s: start=%d, end=%d, replacement=`%s`",
                filepath,
                start,
                end,
                replacement_text,
            )
            code_bytes = code_bytes[:start] + replacement_bytes + code_bytes[end:]

        # Write the modified content back to the file.
        with open(filepath, "wb") as f:
            f.write(code_bytes)


def _handle_combine(args: argparse.Namespace) -> None:
    """
    Reads multiple files and merges them.
    """
    combined_entries: List[str] = []

    for input_path in args.inputs:
        try:
            with open(input_path, "r", encoding="utf-8") as f:
                data = f.read()
                combined_entries.append(data)

        except IOError as e:
            print(f"Error merging {input_path}: {e}", file=sys.stderr)
            sys.exit(1)

    with open(args.output_file, "w", encoding="utf-8") as f:
        f.write("\n".join(combined_entries))


def main() -> None:
    parser = _create_parser()

    # parse_known_args is critical here!
    # It parses known flags (-o, -i, -e) and leaves the rest in 'unknown'.
    # This 'unknown' list contains the actual compiler command we need to capture.
    args, unknown = parser.parse_known_args()
    _setup_logging(args.verbose)

    logging.debug("Starting clang-tidy utility in %s mode.", args.mode)
    logging.debug("Received args: %s", args)
    logging.debug("Received unknown args: %s", unknown)

    if args.mode == "generate":
        _handle_generate(args, compiler_flags=unknown)
    elif args.mode == "fix":
        _apply_fixes(yaml_files=args.yaml, sed=args.re, cwd=args.C)
    elif args.mode == "combine":
        _handle_combine(args)


if __name__ == "__main__":
    main()
