# Package dedicated to rules for gathering license and package metadata.
load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "merge_metadata",
    srcs = ["merge_metadata.py"],
)
