load("@rules_python//python:defs.bzl", "py_binary")

package(
    default_applicable_licenses = ["//:license"],
    default_visibility = ["//visibility:public"],
)

py_binary(
    name = "parallel_zip",
    srcs = ["parallel_zip.py"],
    visibility = ["//visibility:public"],
)

alias(
    name = "7za",
    actual = "@sevenzip//:7za",
    visibility = ["//visibility:public"],
)
