load("@bazel_skylib//rules:common_settings.bzl", "bool_flag")

package(default_visibility = ["//visibility:public"])

bool_flag(
    name = "hermetic_msvc",
    build_setting_default = False,
    scope = "universal",
)

toolchain_type(
    name = "resource_compiler_toolchain_type",
    visibility = ["//visibility:public"],
)

alias(
    name = "msdia",
    actual = "@toolchain_hub//cc/windows_clang:msdia",
)
